### ISSUE TITLE
test 10.4.2

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_methodologie#1]
il manque la mention du px dans les unités

**Comment by Etat-Plateforme** [comment]
Comme il est précisé dans le référentiel technique (http://references.modernisation.gouv.fr/referentiel-technique-0#taille-des-caractres), l'utilisation du pixel est proscrite pour les tailles de caractères.

**Comment by goetsu** [comment]
oui ce qui n'est pas indiqué dans la méthodologie : 
"Vérifier que la taille de police est exprimée uniquement avec des unités relatives : %, em, rem, vw, vh, vmin, vmax pour les types de média screen, tv, handheld, projection."
