### ISSUE TITLE
fichier css utilisateur

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_methodologie#3]
la méthodologie mentionne des fichiers css utilisateurs types check-heading.css ils ne semblent pas disponible au téléchargement

**Comment by philippeBron** [comment]
Les fichiers css ont été ajouté au dépôt. La synchronisation avec gh-page sera fait demain car ils ne sont pas nécessaires à la lecture de la documentation.
Désolé pour cet oubli et merci de ta vigilance @goetsu .
