### ISSUE TITLE
Liste document bureautique en téléchargement

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_methodologie#4]
Dans la note du "Tests 13.7.1, 13.8.1", il est mentionner : Seules les erreurs relatives à des critères présents dans la listes des critères « Liste document bureautique en téléchargement ». Par contre, il semble que cette liste ne soit pas publiée. Le seul trouvé sur le net (https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0ahUKEwiXyOad45TKAhVE1BoKHZuSCRIQFggvMAI&url=https%3A%2F%2Freferences.modernisation.gouv.fr%2Fsites%2Fdefault%2Ffiles%2Fliste-criteres-documents-bureautiques-telechargement-RGAA.odt&usg=AFQjCNEkIr4l_wtbVU-07sVbb3MxJ-J5uQ&sig2=z-NOPwtef-RMWYBjL0aqhQ&cad=rja) est a priori un document de travail car bien qu'il mentionne le RGAA 3.0 (avec un date de janvier 2010 ?) propose des critères avec des niveaux bronze... Y a-t-il un document officiel (mettre le lien) ou une date de sortie (mettre la date) ?
Cordialement

**Comment by OlivierNourry** [comment]
Bonjour Giuseppe,
Le RGAA 3 comporte bien une liste de critères bureautiques, trouvable à partir du glossaire: http://references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#version-accessible-document 

(PS: désolé pour la réponse tardive, cette issue m'avait échappé)
