### ISSUE TITLE
Test 6.1.3

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_methodologie#5]
la méthodologie vérifie le contenu des attribut alt des area alors que le test devrait porter sur les liens servant d'alternative à une image map coté serveur.

Certes l'alternative peut elle même passer par une image map coté client mais c'est généralement plutot des liens textes dans la page. A minima il faut prévoir ce cas.
[code correspondant](https://github.com/DISIC/rgaa_methodologie/blob/master/index.html#L2522-L2552)

**Comment by goetsu** [comment]
idem pour  [6.2.3](https://github.com/DISIC/rgaa_methodologie/blob/master/index.html#L2626-L2658), [6.3.3](https://github.com/DISIC/rgaa_methodologie/blob/master/index.html#L2734-L2765)

**Comment by Etat-Plateforme** [comment]
Le RGAA demande effectivement via le test 1.1.4 à ce que chaque zone cliquable d'une image réactive coté serveur soit doublée d'un lien dans la page. Mais ces liens deviennent alors des liens à part entière et sont alors à tester avec les tests relatifs aux types de liens auxquels correspondent ces « liens alternatifs ». Dans les tests 6.*.3, on teste la pertinence des zone `area`. 

Nous ne voyons pas de raison de modifier cette position.
