### ISSUE TITLE
Coquille dans check-css/check-structure.css

### ISSUE THREAD

**Issue by florian-sanders** [DISIC/rgaa_methodologie#6]
Un détail mais les guillemets anglaises sont placées après les chevrons de fin de balise dans le fichier.

Par exemple : 

```
header:before{
                content:'<header role="'attr(role)'>"';
}
```

![check-structure_guillemets](https://cloud.githubusercontent.com/assets/20340773/16657817/1c771ca6-4464-11e6-81b8-ccd30bba1562.png)

**Comment by Etat-Plateforme** [comment]
Coquille corrigée avec la dernière mise à jour.
