### ISSUE TITLE
Test 1.2.4

### ISSUE THREAD

**Issue by okeul** [DISIC/rgaa_methodologie#7]
Il y a une coquille sur le test 1.2.4 qui demande de vérifier la présence de la propriété ARIA `role="img"` sur la balise svg.

Avec la WAT :
https://github.com/DISIC/rgaa_methodologie/blob/master/index.html#L287

Avec la WebDev :
https://github.com/DISIC/rgaa_methodologie/blob/master/index.html#L305

Le [test 1.2.4](http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#test-1-2-4) du RGAA 3 2016 demande de vérifier la présence de la propriété ARIA `aria-hidden="true"` sur la balise svg (et non `role="img"`).

**Comment by Etat-Plateforme** [comment]
Bonjour,

Merci pour votre commentaire.

Nous ne comprenons pas bien la demande :

Le test 1.2.4 du RGAA demande la présence de la propriété aria-hidden="true" sur la balise "svg"
https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#test-1-2-4

La procédure pour le test 1.24 de la méthodologie demande également de vérifier la présence de la propriété aria-hidden="true" sur la balise "svg"
http://disic.github.io/rgaa_methodologie/#test-1.2.4

Nous ne voyons pas où il est fait référence au role="img".

Pourriez-vous nous apporter plus de précisions ?
